### ISSUE TITLE
Option arguments should be treated differently

### ISSUE THREAD

**Issue by ObserverOfTime** [tree-sitter/tree-sitter-bash#130]
Option arguments (`-foo --bar`) should not be mapped to `argument: (word)` like other arguments.

For example, this script produces the following syntax tree:

```bash
cmake . --fresh -B build -DCMAKE_BUILD_TYPE=Release
```

```
(program
  (command
    name: (command_name
      (word))
    argument: (word)
    argument: (word)
    argument: (word)
    argument: (word)
    argument: (word)))
```
I think it'd be better if options were differentiated with something like this:
```
(program
  (command
    name: (command_name
      (word))
    argument: (word)
    argument: (option)
    argument: (option)
    argument: (option  
      operator: '='
      value: (word))))
 ```

**Comment by amaanq** [comment]
from a parsing pov, are there contexts in which optional arguments are/aren't allowed vs regular arguments? 

If not, I'd think differentiating them w/ queries is better

**Comment by ObserverOfTime** [comment]
> from a parsing pov, are there contexts in which optional arguments are/aren't allowed vs regular arguments?

Many commands treat `--` as the end of options, so any options after that are parsed as regular arguments.

> If not, I'd think differentiating them w/ queries is better

It's possible to differentiate the entire argument, but not its name and value separately.

**Comment by amaanq** [comment]
I see, but while that does apply to a lot of commands it doesn't to all of them..

consider this:
```sh
cargo run --bin a -- --help
```

The options before -- are for the cargo, the ones after are for the binary itself. Aren't both options in this case?

**Comment by verhovsky** [comment]
tree-sitter-bash should not do this because this kind of parsing doesn't happen in Bash. Bash does variable substitution and calls subcommands, but ultimately it calls programs with a list of string arguments like `["cargo", "run", "--bin", "a", "--", "--help"]` and then it's up to the program to parse that list of strings as it wants. There's a set of conventions that programmers follow about how programs should parse those arguments (namely `-` followed by a letter, `--` followed by full words and `--` on its own to signal the end of arguments and the start of raw string arguments even if some start with `-`) but again that parsing doesn't happen in Bash itself and other programs could do different things.
