### ISSUE TITLE
Missing reserved words

### ISSUE THREAD

**Issue by jaopaulolc** [tree-sitter/tree-sitter-bash#133]
Hi,

I notice that the grammar does not include some reserved words that are part of the language according to the [Bash Reference Manual](https://www.gnu.org/software/bash/manual/bash.html). 

This is a list of some with some reserved words that are missing:

`("time" "coproc" "type" "trap" "exit" "exec" "continue" "break" "return" "logout" "bye" "true" "false" "test")`

My suspicion is that including those would complicate significantly the parser and that my be the reason to leave those out.

However, for fontification and other text editing tasks, it is desirable to identify those.

Is the recommend approach to use a generic query and a regex to find the above reserved words? Something like this:

`(command_name ((word) @captured_keyword (#match? @captured_keyword <regex to reserved words>)))`

**Comment by Ordoviz** [comment]
`type`, `test`, `true`, `false`, and `logout` are just builtins, while `exec`, `exit`, `return`, `break`, and `continue` are "[special shell builtins](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_14)",  which cannot be used as function names in `--posix` mode.

I support adding the `select` and `until` keywords and the listed special builtins to the [`@keyword` array](https://github.com/tree-sitter/tree-sitter-bash/blob/b338fa9f4807b9e0336cd4dde04948a8c324a4cf/queries/highlights.scm#L12-L28) since they change control flow so making them stand out would aid reading.

A complete list of keywords and builtins can be generated with `compgen -k` and `compgen -b`, respectively.

**Comment by verhovsky** [comment]
I added `select` and `until` as keywords since they make sense as keywords and they're returned by `compgen -k`. I don't have an opinion on including `exec`, `exit`, `return`, `break`, and `continue` so I won't close the issue.

**Comment by amaanq** [comment]
bye is a zsh builtin in my case

The others are not exposed literals, so no point adding them as keywords unless they're separate statement rules
