### ISSUE TITLE
Error parsing GitHub actions `run:` section

### ISSUE THREAD

**Issue by disrupted** [tree-sitter/tree-sitter-bash#253]
I originally opened an issue at https://github.com/nvim-treesitter/nvim-treesitter/issues/6099 but was told to report it here instead.

Inside GitHub actions or workflow YAML files the `run:` section contains shell (bash) code. GitHub has a special syntax for context variables (dollar sign and curly braces), e.g. ${{ context.property }}. Official docs: https://docs.github.com/en/actions/learn-github-actions/variables

It differs from the syntax for regular variables (dollar sign, no curly braces), e.g. $variable.

There I get an ERROR node in the Treesitter tree, which breaks the highlighting.

![Neovim screenshot](https://github.com/tree-sitter/tree-sitter-bash/assets/4771462/eb3671e4-501a-4502-926e-ed6bd0fd5fa1)

**Comment by amaanq** [comment]
It's not really valid **bash** syntax, but rather it's a github-specific implementation. so your options are to either write a "tree-sitter-github-bash" parser that builds on top of this, or live with the parse errors, frankly I would go for the latter since it is just 1 construct that is technically invalid in normal bash files, or edit your action to use env variables with those values and then reference those env variables in your shell code.

**Comment by ObserverOfTime** [comment]
You can just wrap the expressions in quotes if they can't contain multiple arguments.
