### ISSUE TITLE
No parsing for escape sequences like \n in string

### ISSUE THREAD

**Issue by kaddkaka** [tree-sitter/tree-sitter-bash#96]
The parser does not recognize escape sequences in strings which makes things like `\n` have the same color as the rest of the string. 

Other example: tree-sitter-python parser does parse escape sequences inside strings.

**Comment by tmillr** [comment]
I don't believe `\n` is a syntax item or symbol in bash?

AFAIK, bash only recognizes/interprets it within `$''`.

In most other places, `\n` becomes `n`, unless the `\` is quoted.

There are certain commands (including builtins) that will recognize it within its arguments/input, but it depends on the particular command (and even other arguments to the command, argument position, etc.).

If you always want `\n` highlighted differently, there may be a solution/workaround by using something custom highlighting queries, or language injection queries (e.g. capture string literals in bash syntax and inject [regex](https://github.com/tree-sitter/tree-sitter-regex) or a simple custom grammar/language which parses such escapes as separate ts nodes).

**Comment by verhovsky** [comment]
If you're trying to parse ANSI-C quoted strings (strings that look like `$''`) into their value (for example, converting strings like `$'\n'` into a string with a single literal newline character), see/use this code:

https://github.com/curlconverter/curlconverter/blob/dc7dfc7cdc1ff9094ab49507c64aa2b8f5a5a462/src/shell/tokenizer.ts#L23-L102

tree-sitter effectively just labels parts of the input text, it has no code for converting parts of the source code into values. It doesn't even remove quotes for you. So if you have some code like `myvar='foo bar'` and you look at the tree-sitter node of the string it's `.text` value will just be "`'foo bar'`" and it's up to you to parse that further.

I suggested adding a way to tree-sitter to implement getting the semantic value of literals [here](https://github.com/tree-sitter/tree-sitter/issues/1401) because I had to implement it for tree-sitter-bash and it would be nice if other people could use it since it's surely a common thing to want to do (my heuristic is that everything I want to do, lots of other people want to do), but adding something like this to tree-sitter is a lot of work of course.
